question_data = [
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Greenland is covered with grass and Iceland covered with ice.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "The Republic of Malta is the smallest microstate worldwide.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Vatican City is a country.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "San Marino is the only country completely surrounded by another country.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Ottawa is the capital of Canada.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "St. Louis is the capital of the US State Missouri.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Tokyo is the capital of Japan.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Hungary is the only country in the world beginning with H.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Rhode Island is actually located on the US mainland, despite its name.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]


# data from open trivia db api